Vagrant.configure("2") do |config|
  # Control node: Debian (где запускаем ansible)
  config.vm.define "ansible" do |a|
    a.vm.box = "debian/bookworm64"
    a.vm.hostname = "ansible"
    a.vm.network "private_network", ip: "192.168.56.50"
    a.vm.provider "virtualbox" do |vb|
      vb.name = "lesson13-ansible"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # DB node
  config.vm.define "db" do |d|
    d.vm.box = "generic/rocky9"
    d.vm.hostname = "db"
    d.vm.network "private_network", ip: "192.168.56.51"
    d.vm.provider "virtualbox" do |vb|
      vb.name = "lesson13-db"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Web node: Ubuntu (проверяем Debian family)
  config.vm.define "web" do |w|
    w.vm.box = "ubuntu/jammy64"
    w.vm.hostname = "web"
    w.vm.network "private_network", ip: "192.168.56.52"
    w.vm.provider "virtualbox" do |vb|
      vb.name = "lesson13-web"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
