---
- name: Apache | Install for Debian family
  import_tasks: debian.yml
  when: ansible_facts['os_family'] | lower == 'debian'

- name: Apache | Install for RedHat family
  import_tasks: redhat.yml
  when: ansible_facts['os_family'] | lower == 'redhat'
