apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "codebywp.mysql.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
{{ include "codebywp.labels" . | indent 4 }}
spec:
  serviceName: {{ include "codebywp.mysql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "codebywp.name" . }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image | quote }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "codebywp.fullname" . }}-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "codebywp.fullname" . }}-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "codebywp.secretName" . }}
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "codebywp.secretName" . }}
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "codebywp.mysql.fullname" . }}-pvc
