apiVersion: v1
kind: Service
metadata:
  name: {{ include "codebywp.mysql.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
{{ include "codebywp.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
