{{- if not .Values.secrets.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codebywp.secretName" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
{{ include "codebywp.labels" . | indent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
{{- end }}
