apiVersion: v1
kind: Service
metadata:
  name: {{ include "codebywp.wp.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
{{ include "codebywp.labels" . | indent 4 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  selector:
    app: wordpress
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      {{- if eq .Values.wordpress.service.type "NodePort" }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
      {{- end }}
