Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # ВАЖНО: оставляем стандартный ключ Vagrant, чтобы Ansible мог подключаться
  # одним и тем же приватным ключом ~/.vagrant.d/insecure_private_key
  config.ssh.insert_key = false

  config.vm.define "dev" do |d|
    d.vm.hostname = "dev"
    d.vm.network "private_network", ip: "192.168.56.40"
  end

  config.vm.define "prod" do |p|
    p.vm.hostname = "prod"
    p.vm.network "private_network", ip: "192.168.56.41"
  end

  config.vm.define "ansible" do |a|
    a.vm.hostname = "ansible"
    a.vm.network "private_network", ip: "192.168.56.42"
  end

end
