apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: dev
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-sc
  volumeName: pv-wordpress
  resources:
    requests:
      storage: 1Gi
