apiVersion: v1
kind: Secret
metadata:
  name: wp-secrets
  namespace: dev
type: Opaque
stringData:
  mysql-root-password: CHANGE_ME
  mysql-database: wordpress
  mysql-user: wpuser
  mysql-password: CHANGE_ME
