Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "server" do |s|
    s.vm.hostname = "server"
    s.vm.network "private_network", ip: "192.168.56.30"
  end

  config.vm.define "store" do |st|
    st.vm.hostname = "store"
    st.vm.network "private_network", ip: "192.168.56.31"
  end
end
